### PR TITLE
Remove subsetter (codepoint) related stuff

### PR DESCRIPTION
**Pull request by simoncozens**
For simplicity we are moving all the *codepoint* related code and data to the `nam-files` repository (which should at one point be renamed "gfsubsets"), leaving all the *glyphset* (Glyphs files, glyph definitions, etc.) related code and data here.

~To be merged when the `gfsubsets` Python module is published.~

### CODE REVIEW

**Comment by yanone** [comment]
Meanwhile I changed the formatting (and content of `install_requires`) of `setup.py` in main, so now there's a conflict. So sorry.

**Comment by yanone** [comment]
Simon, I did some code searches on Github:
[from glyphsets import codepoints](https://github.com/search?q=%22from+glyphsets+import+codepoints%22+language%3APython&type=code)
[from glyphsets.subsets import](https://github.com/search?q=%22from+glyphsets.subsets+import%22+language%3APython&type=code)

All except one instance are FB forks, so we can ignore those. The current FB is already rewired to the new repo.

The exception is [gftools](https://github.com/googlefonts/gftools/blob/d2ec65daee994cd4c9b5461845ba749222088254/Lib/gftools/util/google_fonts.py#L168). This is the only place that must get rewired to the new subsets package.

Therefore, I would like to ask you to cleanly remove all references to the subsets. I'll create an issue at gftools.

**Comment by yanone** [comment]
Err, there is also [from glyphsets.codepoints import](https://github.com/search?q=%22from+glyphsets.codepoints+import%22+language%3APython&type=code&p=1) which is a bit more extensive. I just tried to do a PR on gftools to rewire everything, but at least one method (`CodepointsInNamelist()`) hasn't made it into the new subsets package, so I can't simply complete the PR.

**Comment by simoncozens** [comment]
D'oh, I thought I did a gftools PR already, but apparently not. I'll do one. The tool which uses `CodepointsInNamelist` is dead and should be removed.

**Comment by simoncozens** [comment]
PR for removal in gftools: https://github.com/googlefonts/gftools/pull/822

**Comment by simoncozens** [comment]
gftools latest release has this PR now, so we should be good to go.

**Comment by yanone** [comment]
> so we should be good to go.

Please finalize this PR by removing all remaining gfsubset references

**Comment by yanone** [comment]
This looks very complete now. Are you done from your side?

**Comment by simoncozens** [comment]
Yep, I'm happy.

**Comment by yanone** [comment]
Thank you

**Pull request merged**
