### PR TITLE
Move Cyrillic Pro to language-based

### PR DESCRIPTION
**Pull request by simoncozens**

### CODE REVIEW

**Comment by yanone** [comment]
I’m not tagged as a reviewer, but I have a comment anyway:

I would like to ask to preserve in the glyphset description the languages that aren’t currently defined in _gflanguages_ and thus can’t be included at this point so that they can be restored later when they are defined, or can be inferred from a different data source such as _hyperglot_ (which we could consider as a secondary data source anyway btw).

Once you're at it, please replace the entire description text with something meaningful. The headline typefaces note is nonsense, and so is the Slavic languages note. Many of these languages have no relation to Slavic.

**Comment by moyogo** [comment]
There is data in gflanguages for other Non-Slavic languages. Should they be added to GF_Cyrillic_Pro?

**Comment by yanone** [comment]
Are you asking to add _all_ remaining defined Cyrillic languages to Cyrillic Pro or still just a subset?

**Comment by moyogo** [comment]
@yanone Are you asking to add all remaining defined Cyrillic languages to Cyrillic Pro or still just a subset?

I don’t know what the rationale is for this GF glyphsset besides "other Non-Slavic". If the set is defined as the current list of languages then my question is: should there be a GF_Cyrillic_Beyond with all remaining defined Cyrillic languages.

**Comment by yanone** [comment]
> I don’t know what the rationale is for this GF glyphset besides "other Non-Slavic"

We should ask this question in the chat, because I think around here nobody knows the answer.
Personally I will postpone that as I'm still on vacation. I had merged a few simple PRs earlier today and skimmed over this one.

We also don't need to keep this glyphset around at all if nobody knows why it exists, and resurrect a new one with a clear definition once we have a use case, as the assembly is so swift nowadays.

**Comment by vv-monsalve** [comment]
Hi @simoncozens 

I've completed the cross-reference between the modifications made for the 'Cyrillic Pro' subset, the current 'Cyrillic Plus' list, and the language support in Playpen Sans.

The plan is to update the `GF Cyrillic Plus` definition using the list of languages currently supported by Playpen Sans, based on TT's revision to the current Plus glyphset. The font indeed supports many of the languages [currently listed in Cyrillic Plus](https://github.com/googlefonts/glyphsets/blob/main/GLYPHSETS.md#gf-cyrillic-plus), while only a few languages listed in this PR for `Cyrillic Pro` are "nearly supported" and the others are not supported at all.

We can still use this PR to redefine the `Pro`, but we must also redefine the `Plus`. However, it would be key to establish criteria that could help define glyph sets. We could consider using a language population filter to better distinguish 'Plus' from 'Pro', instead of solely relying on the "Slavic" versus non-Slavic categorization.

What was your criteria for the current list of languages ​​included in this “Pro” redefinition?

Below is the lists of supported languages by Playpen Sans.

## Playpen Sans supported Cyrillic languages


#### GF_Cyrillic_Core

be_Cyrl (Belarusian)
bs_Cyrl (Bosnian (Cyrillic))
bg_Cyrl (Bulgarian)
ru_Cyrl (Russian)
sr_Cyrl (Serbian)
uk_Cyrl (Ukrainian)


#### Languages that could inform the GF Cyrillic Plus redefinition
abq_Cyrl (Abaza) 
ady_Cyrl (Adyghe)
av_Cyrl (Avaric)
bua_Cyrl (Buriat)
ce_Cyrl (Chechen)
cjs_Cyrl (Shor)
crh_Cyrl (Crimean Turkish, Cyrillic)
dar_Cyrl (Dargwa)
dng_Cyrl (Dungan)
gag_Cyrl (Gagauz (Cyrillic))
inh_Cyrl (Ingush)
kbd_Cyrl (Kabardian)
kaa_Cyrl (Kara-Kalpak)
kk_Cyrl (Kazakh)
koi_Cyrl (Komi-Permyak)
krc_Cyrl (Karachay-Balkar)
kum_Cyrl (Kumyk)
kv_Cyrl (Komi)
ky_Cyrl (Kyrgyz)
lez_Cyrl (Lezghian)
mdf_Cyrl (Moksha)
mn_Cyrl (Mongolian)
mrj_Cyrl (Western Mari)
nog_Cyrl (Nogai)
ro_Cyrl (Romanian (Cyrillic))
rue_Cyrl (Rusyn)
tab_Cyrl (Tabassaran)
tg_Cyrl (Tajik)
tk_Cyrl (Turkmen (Cyrillic))
tkr_Cyrl (Tsakhur)
ttt_Cyrl (Muslim Tat)
udm_Cyrl (Udmurt)
ug_Cyrl (Uyghur (Cyrillic))
uz_Cyrl (Uzbek (Cyrillic))
xal_Cyrl (Kalmyk)



### Nearly supported languages

#### Simon’s Cyrillic Pro proposal
evn_Cyrl (Evenki)
kpy_Cyrl (Koryak)
mns_Cyrl (Mansi)
yrk_Cyrl (Nenets)
sah_Cyrl (Sakha)

#### Other nearly supported languages

aii_Cyrl (Assyrian Neo-Aramaic, Cyrillic)
alt_Cyrl (Southern Altai)
az_Cyrl (Azerbaijani (Cyrillic))
chm_Cyrl (Mari)
cv_Cyrl (Chuvash)
gld_Cyrl (Nanai)
kjh_Cyrl (Khakas)
os_Cyrl (Ossetic)
tly_Cyrl (Talysh (Cyrillic))

**Comment by vv-monsalve** [comment]
I've opened a PR to redefine [GF_Cyrillic_Plus](https://github.com/googlefonts/glyphsets/pull/227) based on a combination of languages and + number of speakers, regardless of whether they are Slavic.

**Comment by yanone** [comment]
Is this one ready to go as well next to the recent Core and Plus redefintions @simoncozens and @vv-monsalve?

**Comment by simoncozens** [comment]
Yes, I think that's the right strategy - I was just trying to copy the old system, but now we are doing something different.

**Pull request closed without merging**
