### PR TITLE
Update `emoji_unique-glyphs.nam` with 0x2713 CHECK MARK 

### PR DESCRIPTION
**Pull request by vv-monsalve**
Hi @garretrieger,

Playpen Sans now includes new codepoints for its emojis, and we are going to use the "emoji" subset instead of the previous "symbols". 

This PR includes the `0x2713 CHECK MARK` codepoint necessary to support Playpen Sans.

cc @chrissimpkins

### CODE REVIEW

**Comment by garretrieger** [comment]
Adding Nyshadh to take a look and update the internal emoji nam file.

**Comment by vv-monsalve** [comment]
It belongs to the [Dingbats](https://unicode.org/charts//PDF/Unicode-3.2/U32-2700.pdf) block along with other codepoints already included in this encoding. 
All 2700 to 27BF like `0x270F PENCIL`, `0x274C CROSS MARK`

**Comment by rsheeter** [comment]
The emoji subset is not meant to include things that aren't emoji. Emoji unfortunately do not form a nice block or blocks. I see the checkmark in symbols, why don't we use that?

**Comment by vv-monsalve** [comment]
Everything included in the Playpen Sans font was required to be considered emoji, and to assign existing codepoints to them.
As part of that process, we searched for a unified subset that could include all the necessary codepoints, given we already serve emoji fonts. We found this `emoji` subset to be the most complete one, bigger than `symbols`, which was missing only this single codepoint.
One of the @chrissimpkin concerns was precisely to avoid any misleading use of a symbols subset for emojis.

**Comment by rsheeter** [comment]
Will followup in IM; please do not merge.

**Comment by simoncozens** [comment]
If needed, please re-open in https://github.com/googlefonts/nam-files (but it doesn't seem like it is.)

**Pull request closed without merging**
