### PR TITLE
[nam] Add combining marks to Latin, ext Latin and Vietnamese

### PR DESCRIPTION
**Pull request by simoncozens**
See #98

### CODE REVIEW

**Comment by garretrieger** [comment]
In general we can't have code points duplicated between different subsets. Since unicode-range range will result in the codepoint being used from only one subset at a time. For the case of #98 the issue can be solved by adding the combining marks to only latin.

I've been testing this internally with smaller set of additions, just

0x0300
0x0301
0x0303
0x0304
0x0309
0x0323
0x0329

And that seems to fix the reported issue. We have one issue we're figuring out, where adding these to Roboto causes a significant jump in the subset size (+20%). So we need to solve that before we can proceed with updating the subset definitions.

**Comment by simoncozens** [comment]
> In general we can't have code points duplicated between different subsets. 

We will need to. Combining marks can be used with multiple scripts, including between Latin and IPA for African languages.

**Comment by garretrieger** [comment]
> > In general we can't have code points duplicated between different subsets.
> 
> We will need to. Combining marks can be used with multiple scripts, including between Latin and IPA for African languages.

Do you have some sample text that requires the combining marks to be present in latin-ext? I need to check if browsers correctly assign the combining marks to the right subset when utilizing unicode-range and there is combining marks in both latin and latin-ext.

**Comment by simoncozens** [comment]
> Do you have some sample text that requires the combining marks to be present in latin-ext?

`hna_Latn` has `gbèsɔɛ́mɛ́wó nɔ́visilélé`. 

Perhaps a better examples that Vietnamese and Tamazight both use the combining dot below accent. Vietnamese has `độ` while `tzm_Latn` has `lḥeqq ubeggen n ṛṛay`.

If you want a fun one, combining diaeresis is used in both Latin and Cyrillic: `thɛ̈kic` in `dip_Latn` and `кандёрива` in `gld_Cyrl`.

Also anything with script extensions should appear in all scripts that support that extension; the idea that one codepoint belongs to one script is just not how Unicode works. For example

```
# Script_Extensions=Adlm Arab Mand Mani Ougr Phlp Rohg Sogd Syrc

0640          ; Adlm Arab Mand Mani Ougr Phlp Rohg Sogd Syrc # Lm       ARABIC TATWEEL
```

As this character takes part in shaping, it needs to be present in all those subsets.

**Comment by garretrieger** [comment]
Alright, I put together a test page with the various strings and confirmed that everything works correctly in the major browsers when the combining marks are in all 3 subsets. So looks like we'll be good to add them to all 3.

**Comment by garretrieger** [comment]
So for now I ended up adding a subset of these to our internal versions of the latin, latin-ext, and vietnamese subsets that cover all of the cases I've seen so far:

0x0300    COMBINING GRAVE ACCENT
0x0301    COMBINING ACUTE ACCENT
0x0303    COMBINING TILDE
0x0304    COMBINING MACRON
0x0308    COMBINING DIAERESIS
0x0309    COMBINING HOOK ABOVE
0x0323    COMBINING DOT BELOW
0x0329    COMBINING VERTICAL LINE BELOW

Families will need to be version bumped to actually pick up the changes, but since these affect most families it may be a bit before we can get the fix out to all families. For now I've updated Noto Sans, Andika, Charissil, and Gentium Plus which were specifically mentioned in #98. If there's other families that you'd like the get the updates sooner let me know and I can get them version bumped.

**Comment by jvgaultney** [comment]
Thanks - this gets Yoruba working, however Vietnamese is still broken. There are sequences that contain U+0302 COMBINING CIRCUMFLEX, specifically `ộ` and `ậ`, that still don't render using the font. This is example 1 in my [original bug reports from last year](https://github.com/google/fonts/issues/5385). Here's a snapshot again:

image

There is also the larger problem of many, many more extended Latin characters and combining marks that remain broken. See example 3 in my bug reports.

**Comment by garretrieger** [comment]
> Thanks - this gets Yoruba working, however Vietnamese is still broken. There are sequences that contain U+0302 COMBINING CIRCUMFLEX, specifically `ộ` and `ậ`, that still don't render using the font. This is example 1 in my [original bug reports from last year](https://github.com/google/fonts/issues/5385). Here's a snapshot again:
> 
> image
> 
> There is also the larger problem of many, many more extended Latin characters and combining marks that remain broken. See example 3 in my bug reports.

Thanks for the update, after launching the the updated combining mark subsets a couple of days ago on a few families we found some regressions which required us to remove 0x0323 (and others) from the latin and latin-ext unicode range string. Unfortunately this affects 0x00F4 + 0x0323 combination since 0x00F4 resides in the latin subset (The combining mark is in the subset now, but since the unicode range string doesn't declare it the browser won't attempt to render 0x00F4 + 0x0323 within latin). See this codepen which shows the codepoint working with the latin subset: https://codepen.io/garretrieger/pen/gOBozMX. This also impacts the some of the other latin codepoints from your report.

We're currently working on coming up with a update to the subsets and unicode range definitions to try and get everything working correctly.

**Comment by RosaWagner** [comment]
@garretrieger can you push back your changes into this repo in a separated PR? we are a bit lost.

**Comment by garretrieger** [comment]
Yes, I'll update this to match the changes we made internally. We're still figuring out exactly what we're going to do but might as well update this to match the current state for now.

**Comment by garretrieger** [comment]
> Yes, I'll update this to match the changes we made internally. We're still figuring out exactly what we're going to do but might as well update this to match the current state for now.

PR created here: #110

**Pull request closed without merging**
