### PR TITLE
GF Latin African

### PR DESCRIPTION
**Pull request by moyogo**
This replaces #134  SSA latin all changes and #142 with the glyphsets.definitions model for GF_Latin_African.

### CODE REVIEW

**Comment by yanone** [comment]
Also, please add the glyphset name to the manually curated list at the top in /README.md that points out which of the glyphsets are getting assembled under the new approach.

**Comment by yanone** [comment]
Please note that the actual contents of the .nam/etc. files that are being affected here I cannot review because I lack the knowledge of the languages. We need to trust the code and gflanguages now. Please review these carefully yourself. Obviously, they now include lots of basic Latin letters as well since they're defined for each language.

If that's a problem and these glyphsets are truly meant to be lean, we could opt to remove duplicates in `assembly_charactersets.py` by defining inheritances. Personally I don't care for the duplicates. Since they are actually defined for these languages, why not have them in the glyphset?

**Comment by moyogo** [comment]
> Also, please add the glyphset name to the manually curated list at the top in /README.md that points out which of the glyphsets are getting assembled under the new approach.

Done

**Comment by moyogo** [comment]
> If that's a problem and these glyphsets are truly meant to be lean, we could opt to remove duplicates in `assembly_charactersets.py` by defining inheritances. Personally I don't care for the duplicates. Since they are actually defined for these languages, why not have them in the glyphset?

There was code to extend other glyphsets and not include all characters in #142. I don’t care either way. There was no strong preference for it either in #137.

**Comment by yanone** [comment]
> There was code to extend other glyphsets and not include all characters in #142. I don’t care either way. There was no strong preference for it either in #137.

So then let's leave it as it is now and react once inheritance/exclusions become necessary.

**Review by yanone — CHANGES_REQUESTED** [review]
@moyogo

**Review by yanone — APPROVED** [review]

**Pull request merged**
