### PR TITLE
Move ExtIPA chars to Phonetics_DisorderedSpeech

### PR DESCRIPTION
**Pull request by moyogo**
There are still a few extIPA characters that should be moved to GF_Phonetics_DisorderedSpeech.

Move ExtIPA symbols from GF_Phonetics_Disorderedspeech to GF_Phonetics_DisorderedSpeech:
- fengdigraph U+2A9 ʩ
- exclamdown U+00A1 ¡
- asterisk U+002A *
- parenleftinferior U+208D ₍
- parenrightinferior U+208E ₎

Remove from GF_Phonetics_IPAStandard, already in
GF_Phonetics_DisorderedSpeech:
- bidentalpercussive U+02AC ʬ
- bilabialpercussive U+02AD ʭ
- lsdigraph U+02AA ʪ
- lzdigraph U+02AB ʫ
- unaspiratedmod U+02ED ˭
- voicingmod U+02EC ˬ
- gbridgeabovecomb U+0346 ◌͆
- equalbelowcomb U+0347 ◌͇
- leftanglebelowcomb U+0349 ◌͉
- nottildeabovecomb U+034A ◌͊
- homotheticabovecomb U+034B ◌͋
- almostequaltoabovecomb U+034C ◌͌
- arrowleftrightbelowcomb U+034D ◌͍
- arrowupbelowcomb U+034E ◌͎
- arrowdoublerightbelowcomb U+0362 ◌͢

Remove from GF_Phonetics_IPAStandard:
- leftanglebracket_rightanglebracket-math

See:
- https://www.internationalphoneticassociation.org/sites/default/files/extIPA_2016.pdf
- https://www.internationalphoneticassociation.org/IPAcharts/IPA_chart_orig/pdfs/IPA_Kiel_2020_symbollist.pdf

### CODE REVIEW

**Comment by moyogo** [comment]
@RosaWagner I also removed leftanglebracket_rightanglebracket-math. I’m sure where that one came from so I didn’t move it DisorderedSpeech.

**Comment by RosaWagner** [comment]
Ah I actually saw the brackets a lot in use in wikipedia article for American notation:
https://en.wikipedia.org/wiki/Americanist_phonetic_notation
and then in:
https://en.wikipedia.org/wiki/International_Phonetic_Alphabet#Brackets_and_transcription_delimiters

So I don't how much Wikipedia on this subject, maybe additional documentation should be found.

I think in standard IPA glyphset with are missing these:

Capture d’écran 2022-09-16 à 13 46 41

**Comment by moyogo** [comment]
The square brackets [ and ] are used to indicate a phonetic realization, the slash is used to indicate phonemes.
The angle brackets are used to indicate graphemes.
For example, an author can use the following for the French word "trou": spelled ⟨trou⟩, can have the phonemic representation /tru/ which can be realized as [tʁ̥u].
That convension for angle brackets is not specific to IPA, it is often used in works discussing spelling.
But since IPA or other phonetic transcriptions are often used in the same works it make sense to have it in the Phonetic sets.

For the tone letters:
Those ligatures could be added but in practice a lot more may be needed. Noto Sans has 140 of them for example.
A font can also be engineered to build them with contextual substitution/positioning instead of just ligature substitution.
Pysilfont has a script [psftoneletter.py](https://github.com/silnrsi/pysilfont/blob/9efa29a7d128cccd3cdf2fca130922215b873b03/examples/psftoneletters.py) for this kind of more flexible stuff.

**Comment by RosaWagner** [comment]
Then we could have a IPA_Plus set or something with them all, with a link to the script in the readme. Let's merge this in the meanwhile ;)

**Pull request merged**
