### PR TITLE
Test up to date data.json

### PR DESCRIPTION
**Pull request by moyogo**
This adds a test to check that data.json is in sync with the source .glyphs files.

### CODE REVIEW

**Comment by m4rc1e** [comment]
Sorry for the delay. I have no clue why your PRs are not trigging the ci.

**Comment by RosaWagner** [comment]
@moyogo it would be great to test if everything is in sync, including the list files (.txt (glyphset) and .nam (charset)) in GF_Glyphsets

**Comment by davelab6** [comment]
@moyogo were you able to test and confirm everything is in sync?

**Comment by moyogo** [comment]
Made obsolete by #109.

**Pull request closed without merging**
