### PR TITLE
Latin African cleanup

### PR DESCRIPTION
**Pull request by moyogo**
The following glyphs are not used in African orthographies:
```
Adieresismacron
Adotaccent
Adotmacron
Ainvertedbreve
Aringbelow
Astroke
Bdotaccent
Bmacronbelow
Ccedillaacute
Chi-latin
Cstroke
Dcedilla
Ecedillabreve
Ecircumflexbelow
Einvertedbreve
Emacronacute
Emacrongrave
Estroke
Ezhcaron
Fdotaccent
Gacute
Gmacron
Hbrevebelow
Hcaron
Hcedilla
Hdieresis
Heng
Idieresisacute
Iinvertedbreve
Kdotbelow
Kstroke
Lbelt
Ldotbelow
Ldotbelowmacron
Ldoublebar
Lmacronbelow
Lmiddletilde
Mdotaccent
Mdotbelow
Nlongrightleg
OU
Odieresismacron
Odotaccent
Odotaccentmacron
Oinvertedbreve
Omacronacute
Omacrongrave
Oogonek
Oogonekmacron
Otildemacron
Pacute
Pdotaccent
Qhooktail
Rdblgrave
Rdotaccent
Rdotbelow
Rdotbelowmacron
Rinvertedbreve
Rmacronbelow
Sacutedotaccent
Scarondotaccent
Sdotaccent
Sdotbelowdotaccent
Tdiagonalstroke
Tdotaccent
Ucircumflexbelow
Udieresisacute
Udieresiscaron
Udieresisgrave
Udieresismacron
Uinvertedbreve
Umacrondieresis
Vdotbelow
Wdotaccent
Wdotbelow
Xdieresis
Xdotaccent
Ydotaccent
Ymacron
Zcircumflex
Zstroke
adieresismacron
adotaccent
adotmacron
ainvertedbreve
aringbelow
astroke
bdotaccent
bmacronbelow
ccedillaacute
chi-latin
cstroke
dcedilla
ecedillabreve
ecircumflexbelow
einvertedbreve
emacronacute
emacrongrave
estroke
ezhcaron
fdotaccent
gacute
glottalstop
gmacron
hbrevebelow
hcaron
hcedilla
hdieresis
heng
idieresisacute
iinvertedbreve
kdotbelow
kstroke
lbelt
ldotbelow
ldotbelowmacron
ldoublebar
lmacronbelow
lmiddletilde
mdotaccent
mdotbelow
odieresismacron
odotaccent
odotaccentmacron
oinvertedbreve
omacronacute
omacrongrave
oogonek
oogonekmacron
otildemacron
ou
pacute
pdotaccent
qhooktail
rdblgrave
rdotaccent
rdotbelow
rdotbelowmacron
rinvertedbreve
rmacronbelow
sacutedotaccent
saltillo
scarondotaccent
sdotaccent
sdotbelowdotaccent
tdiagonalstroke
tdotaccent
ucircumflexbelow
udieresisacute
udieresiscaron
udieresisgrave
udieresismacron
uinvertedbreve
umacrondieresis
vdotbelow
wdotaccent
wdotbelow
xdieresis
xdotaccent
ydotaccent
ymacron
zcircumflex
zstroke
glottalstopreversed
glottalstopmod
```

The following glyphs were moved to Latin Beyond:
```
Adieresismacron
Adotaccent
Adotmacron
Ainvertedbreve
Bdotaccent
Bmacronbelow
Chi-latin
Einvertedbreve
Estroke
Hcaron
Hdieresis
Iinvertedbreve
Lbelt
Ldoublebar
Mdotaccent
Nlongrightleg
OU
Odieresismacron
Odotaccent
Odotaccentmacron
Oinvertedbreve
Otildemacron
Pacute
Pdotaccent
Qhooktail
Rdblgrave
Rinvertedbreve
Rmacronbelow
Sdotaccent
Udieresisgrave
Uinvertedbreve
Umacrondieresis
Xdieresis
Xdotaccent
Zstroke
Saltillo
adieresismacron
adotaccent
adotmacron
ainvertedbreve
bdotaccent
bmacronbelow
einvertedbreve
estroke
hcaron
hdieresis
iinvertedbreve
ldoublebar
mdotaccent
odieresismacron
odotaccent
odotaccentmacron
oinvertedbreve
otildemacron
ou
pacute
pdotaccent
qhooktail
rdblgrave
rinvertedbreve
rmacronbelow
sdotaccent
udieresisgrave
uinvertedbreve
umacrondieresis
xdieresis
xdotaccent
zstroke
```

The following glyphs were moved to GF TransLatin Arabic:
```
Dcedilla
Hcedilla
dcedilla
hcedilla
```

### CODE REVIEW

**Comment by RosaWagner** [comment]
@moyogo This is a big change, can you take a last look and confirm you are done with the changes?

Can you also update the database and the list file? Last time I had trouble doing it, I wonder if the glyphsets script still work actually.

**Comment by RosaWagner** [comment]
@moyogo it would be good to merge this PR, can you update the database?

**Review by vv-monsalve — APPROVED** [review]

**Comment by vv-monsalve** [comment]
@moyogo, Do you think there could be more changes, or this could be a definitive version?

If the before, we can merge this here and you can continue making the required adjustments until it's finished. 
If the latter, we should merge and then a final PR to the main branch would be needed.

**Comment by RosaWagner** [comment]
Ah I didn't see it was for another branch branch. Then I don't mind merging so we can update also the database and all the lists.

**Comment by EbenSorkin** [comment]
It looks like Eng was removed from the SSA list. Is it possible this was a
mistake?

**Comment by RosaWagner** [comment]
I think Eng was removed from Latin Core (but still not in the release), and need to be added to African and Beyond

**Comment by EbenSorkin** [comment]
I think Eng goes in African and the localized Eng goes in beyond. I’ll
follow up with Denis

**Pull request merged**
