### PR TITLE
Add exclude parameter to glyphset definition, update GF_Latin_African

### PR DESCRIPTION
**Pull request by moyogo**
- Add `exclude` parameter to glyphset definition
- Update GF_Latin_African, excluding languages (de_Latin, en_Latin, es_Latin, fr_Latin, pt_Latin) with unchecked auxiliary characters

GF_Latin_African had unnecessary glyphs coming from the auxiliary sets of those languages (like slong, etc.).

### CODE REVIEW

**Review by yanone — CHANGES_REQUESTED** [review]
Just one minor change request. The rest looks good. After merging I'll rewrite the documentation assembler (for GLYPHSETS.md) to reflect the exclusions, then publish a package.

**Comment by moyogo** [comment]
@yanone you can do the changes you see fit.

**Comment by moyogo** [comment]
@yanone scratch that, I was able to do the requested change.

**Comment by yanone** [comment]
@moyogo In the future, please run the command `sh build.sh` to rebuild the glyphsets, as this contains an additional command to rebuild the documentation in GLYPHSETS.md.

**Comment by moyogo** [comment]
> The failing tests are a result of your changes, but I'll take care of them.

Got broken unrelated fontbakery tests before.

**Comment by moyogo** [comment]
What's the point of that test anyway?

**Comment by yanone** [comment]
I know. This test is new and mainly serves to alert when APIs in glyphsets change that other tools such as Fontbakery interface with. The errors there were not related to your work, no idea.

After your last commit the Fontbakery error was gone and there was an error in the glyphset-specific tests. I'm checking for the length of the languages compiled dynamically for African Latin specifically to make sure the dynamic assembly is functioning correctly, corrected here, just FYI: https://github.com/googlefonts/glyphsets/commit/cd74f8eb4613cdc5a0848dd60c43a69b1906dd12

**Comment by yanone** [comment]
After I started rewriting much of the glyphsets repo, we had problems updating Fontbakery to the new glyphsets API. Now that the Fontbakery unit tests are part of glyphsets Github Actions, we would get alerted of each incompatibility. It eliminates software administration mistakes.

**Pull request merged**
